name: Publish

on:
    push:
        branches:
        - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
            deno-version: v2.x

      - name: Build
        run: deno run build
